
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt:7 (project)"
    message: |
      The target system is: Windows - 10.0 - AMD64
      The host system is: Linux - 6.8.0-59-generic - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:7 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /usr/bin/clang-18 
      Build flags: -fexceptions;-fcxx-exceptions;-D_CRT_SECURE_NO_WARNINGS;--target=x86_64-windows-msvc;-fms-compatibility-version=19.37;-Wno-unused-command-line-argument;-isystem/home/ibrahim/.local/share/Geode/cross-tools/splat/crt/include;-isystem/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/ucrt;-isystem/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/shared;-isystem/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/um;-isystem/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/winrt;-ivfsoverlay/home/ibrahim/Downloads/GrandpaDemon-main/build-win/winsdk_vfs_overlay.yaml
      Id flags:  
      
      The output was:
      1
      /usr/bin/ld: Error: unable to disambiguate: -defaultlib:libcmt (did you mean --defaultlib:libcmt ?)
      clang-18: error: linker command failed with exit code 1 (use -v to see invocation)
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:7 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /usr/bin/clang-18 
      Build flags: -fexceptions;-fcxx-exceptions;-D_CRT_SECURE_NO_WARNINGS;--target=x86_64-windows-msvc;-fms-compatibility-version=19.37;-Wno-unused-command-line-argument;-isystem/home/ibrahim/.local/share/Geode/cross-tools/splat/crt/include;-isystem/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/ucrt;-isystem/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/shared;-isystem/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/um;-isystem/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/winrt;-ivfsoverlay/home/ibrahim/Downloads/GrandpaDemon-main/build-win/winsdk_vfs_overlay.yaml
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.o"
      
      The C compiler identification is Clang, found in:
        /home/ibrahim/Downloads/GrandpaDemon-main/build-win/CMakeFiles/3.28.3/CompilerIdC/CMakeCCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1182 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:247 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:7 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1182 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:247 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:7 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:7 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: /usr/bin/clang++-18 
      Build flags: -fexceptions;-fcxx-exceptions;-D_CRT_SECURE_NO_WARNINGS;--target=x86_64-windows-msvc;-fms-compatibility-version=19.37;-Wno-unused-command-line-argument;-isystem/home/ibrahim/.local/share/Geode/cross-tools/splat/crt/include;-isystem/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/ucrt;-isystem/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/shared;-isystem/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/um;-isystem/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/winrt;-ivfsoverlay/home/ibrahim/Downloads/GrandpaDemon-main/build-win/winsdk_vfs_overlay.yaml
      Id flags:  
      
      The output was:
      1
      /usr/bin/ld: Error: unable to disambiguate: -defaultlib:libcmt (did you mean --defaultlib:libcmt ?)
      clang++-18: error: linker command failed with exit code 1 (use -v to see invocation)
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:7 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /usr/bin/clang++-18 
      Build flags: -fexceptions;-fcxx-exceptions;-D_CRT_SECURE_NO_WARNINGS;--target=x86_64-windows-msvc;-fms-compatibility-version=19.37;-Wno-unused-command-line-argument;-isystem/home/ibrahim/.local/share/Geode/cross-tools/splat/crt/include;-isystem/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/ucrt;-isystem/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/shared;-isystem/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/um;-isystem/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/winrt;-ivfsoverlay/home/ibrahim/Downloads/GrandpaDemon-main/build-win/winsdk_vfs_overlay.yaml
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.o"
      
      The CXX compiler identification is Clang, found in:
        /home/ibrahim/Downloads/GrandpaDemon-main/build-win/CMakeFiles/3.28.3/CompilerIdCXX/CMakeCXXCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1182 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:247 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:7 (project)"
    message: |
      Detecting CXX compiler /showIncludes prefix:
        
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1182 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:247 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:7 (project)"
    message: |
      Detecting CXX compiler /showIncludes prefix:
        
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "/usr/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:7 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/home/ibrahim/Downloads/GrandpaDemon-main/build-win/CMakeFiles/CMakeScratch/TryCompile-v0Kqs2"
      binary: "/home/ibrahim/Downloads/GrandpaDemon-main/build-win/CMakeFiles/CMakeScratch/TryCompile-v0Kqs2"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "/usr/bin/clang-scan-deps-18"
      CMAKE_C_FLAGS: " -fexceptions -fcxx-exceptions -D_CRT_SECURE_NO_WARNINGS --target=x86_64-windows-msvc -fms-compatibility-version=19.37 -Wno-unused-command-line-argument -isystem\"/home/ibrahim/.local/share/Geode/cross-tools/splat/crt/include\" -isystem\"/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/ucrt\" -isystem\"/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/shared\" -isystem\"/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/um\" -isystem\"/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/winrt\" -ivfsoverlay\"/home/ibrahim/Downloads/GrandpaDemon-main/build-win/winsdk_vfs_overlay.yaml\""
      CMAKE_C_FLAGS_DEBUG: "-O0 -g -Xclang -gcodeview"
      CMAKE_EXE_LINKER_FLAGS: " -L\"/home/ibrahim/.local/share/Geode/cross-tools/splat/crt/lib/x86_64\" -L\"/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/lib/ucrt/x86_64\" -L\"/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/lib/um/x86_64\" -L\"/home/ibrahim/Downloads/GrandpaDemon-main/build-win/winsdk_lib_symlinks\""
      CMAKE_OSX_ARCHITECTURES: "x86_64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/home/ibrahim/Downloads/GrandpaDemon-main/build-win/CMakeFiles/CMakeScratch/TryCompile-v0Kqs2'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_fd8f7/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_fd8f7.dir/build.make CMakeFiles/cmTC_fd8f7.dir/build
        gmake[1]: Entering directory '/home/ibrahim/Downloads/GrandpaDemon-main/build-win/CMakeFiles/CMakeScratch/TryCompile-v0Kqs2'
        Building C object CMakeFiles/cmTC_fd8f7.dir/CMakeCCompilerABI.c.obj
        /usr/bin/clang-18   -fexceptions -fcxx-exceptions -D_CRT_SECURE_NO_WARNINGS --target=x86_64-windows-msvc -fms-compatibility-version=19.37 -Wno-unused-command-line-argument -isystem"/home/ibrahim/.local/share/Geode/cross-tools/splat/crt/include" -isystem"/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/ucrt" -isystem"/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/shared" -isystem"/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/um" -isystem"/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/winrt" -ivfsoverlay"/home/ibrahim/Downloads/GrandpaDemon-main/build-win/winsdk_vfs_overlay.yaml"  -O0 -g -Xclang -gcodeview -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -MD -MT CMakeFiles/cmTC_fd8f7.dir/CMakeCCompilerABI.c.obj -MF CMakeFiles/cmTC_fd8f7.dir/CMakeCCompilerABI.c.obj.d -o CMakeFiles/cmTC_fd8f7.dir/CMakeCCompilerABI.c.obj -c /usr/share/cmake-3.28/Modules/CMakeCCompilerABI.c
        Linking C executable cmTC_fd8f7.exe
        /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_fd8f7.dir/link.txt --verbose=1
        /usr/bin/clang-18 -fuse-ld=lld-link -nostartfiles -nostdlib  -fexceptions -fcxx-exceptions -D_CRT_SECURE_NO_WARNINGS --target=x86_64-windows-msvc -fms-compatibility-version=19.37 -Wno-unused-command-line-argument -isystem"/home/ibrahim/.local/share/Geode/cross-tools/splat/crt/include" -isystem"/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/ucrt" -isystem"/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/shared" -isystem"/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/um" -isystem"/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/winrt" -ivfsoverlay"/home/ibrahim/Downloads/GrandpaDemon-main/build-win/winsdk_vfs_overlay.yaml"  -O0 -g -Xclang -gcodeview -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd  -L"/home/ibrahim/.local/share/Geode/cross-tools/splat/crt/lib/x86_64" -L"/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/lib/ucrt/x86_64" -L"/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/lib/um/x86_64" -L"/home/ibrahim/Downloads/GrandpaDemon-main/build-win/winsdk_lib_symlinks"  -Xlinker /subsystem:console @CMakeFiles/cmTC_fd8f7.dir/objects1.rsp -o cmTC_fd8f7.exe -Xlinker /MANIFEST:EMBED -Xlinker /implib:cmTC_fd8f7.lib -Xlinker /pdb:/home/ibrahim/Downloads/GrandpaDemon-main/build-win/CMakeFiles/CMakeScratch/TryCompile-v0Kqs2/cmTC_fd8f7.pdb -Xlinker /version:0.0  @CMakeFiles/cmTC_fd8f7.dir/linkLibs.rsp 
        clang-18: error: unable to execute command: Executable "lld-link" doesn't exist!
        clang-18: error: linker command failed with exit code 1 (use -v to see invocation)
        gmake[1]: *** [CMakeFiles/cmTC_fd8f7.dir/build.make:102: cmTC_fd8f7.exe] Error 1
        gmake[1]: Leaving directory '/home/ibrahim/Downloads/GrandpaDemon-main/build-win/CMakeFiles/CMakeScratch/TryCompile-v0Kqs2'
        gmake: *** [Makefile:127: cmTC_fd8f7/fast] Error 2
        
      exitCode: 2
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:7 (project)"
    checks:
      - "Check for working C compiler: /usr/bin/clang-18"
    directories:
      source: "/home/ibrahim/Downloads/GrandpaDemon-main/build-win/CMakeFiles/CMakeScratch/TryCompile-Z0vSQj"
      binary: "/home/ibrahim/Downloads/GrandpaDemon-main/build-win/CMakeFiles/CMakeScratch/TryCompile-Z0vSQj"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "/usr/bin/clang-scan-deps-18"
      CMAKE_C_FLAGS: " -fexceptions -fcxx-exceptions -D_CRT_SECURE_NO_WARNINGS --target=x86_64-windows-msvc -fms-compatibility-version=19.37 -Wno-unused-command-line-argument -isystem\"/home/ibrahim/.local/share/Geode/cross-tools/splat/crt/include\" -isystem\"/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/ucrt\" -isystem\"/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/shared\" -isystem\"/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/um\" -isystem\"/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/winrt\" -ivfsoverlay\"/home/ibrahim/Downloads/GrandpaDemon-main/build-win/winsdk_vfs_overlay.yaml\""
      CMAKE_C_FLAGS_DEBUG: "-O0 -g -Xclang -gcodeview"
      CMAKE_EXE_LINKER_FLAGS: " -L\"/home/ibrahim/.local/share/Geode/cross-tools/splat/crt/lib/x86_64\" -L\"/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/lib/ucrt/x86_64\" -L\"/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/lib/um/x86_64\" -L\"/home/ibrahim/Downloads/GrandpaDemon-main/build-win/winsdk_lib_symlinks\""
      CMAKE_OSX_ARCHITECTURES: "x86_64"
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: '/home/ibrahim/Downloads/GrandpaDemon-main/build-win/CMakeFiles/CMakeScratch/TryCompile-Z0vSQj'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_51ffc/fast
        /usr/bin/gmake  -f CMakeFiles/cmTC_51ffc.dir/build.make CMakeFiles/cmTC_51ffc.dir/build
        gmake[1]: Entering directory '/home/ibrahim/Downloads/GrandpaDemon-main/build-win/CMakeFiles/CMakeScratch/TryCompile-Z0vSQj'
        Building C object CMakeFiles/cmTC_51ffc.dir/testCCompiler.c.obj
        /usr/bin/clang-18   -fexceptions -fcxx-exceptions -D_CRT_SECURE_NO_WARNINGS --target=x86_64-windows-msvc -fms-compatibility-version=19.37 -Wno-unused-command-line-argument -isystem"/home/ibrahim/.local/share/Geode/cross-tools/splat/crt/include" -isystem"/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/ucrt" -isystem"/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/shared" -isystem"/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/um" -isystem"/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/winrt" -ivfsoverlay"/home/ibrahim/Downloads/GrandpaDemon-main/build-win/winsdk_vfs_overlay.yaml"  -O0 -g -Xclang -gcodeview -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -MD -MT CMakeFiles/cmTC_51ffc.dir/testCCompiler.c.obj -MF CMakeFiles/cmTC_51ffc.dir/testCCompiler.c.obj.d -o CMakeFiles/cmTC_51ffc.dir/testCCompiler.c.obj -c /home/ibrahim/Downloads/GrandpaDemon-main/build-win/CMakeFiles/CMakeScratch/TryCompile-Z0vSQj/testCCompiler.c
        Linking C executable cmTC_51ffc.exe
        /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_51ffc.dir/link.txt --verbose=1
        /usr/bin/clang-18 -fuse-ld=lld-link -nostartfiles -nostdlib  -fexceptions -fcxx-exceptions -D_CRT_SECURE_NO_WARNINGS --target=x86_64-windows-msvc -fms-compatibility-version=19.37 -Wno-unused-command-line-argument -isystem"/home/ibrahim/.local/share/Geode/cross-tools/splat/crt/include" -isystem"/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/ucrt" -isystem"/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/shared" -isystem"/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/um" -isystem"/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/include/winrt" -ivfsoverlay"/home/ibrahim/Downloads/GrandpaDemon-main/build-win/winsdk_vfs_overlay.yaml"  -O0 -g -Xclang -gcodeview -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd  -L"/home/ibrahim/.local/share/Geode/cross-tools/splat/crt/lib/x86_64" -L"/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/lib/ucrt/x86_64" -L"/home/ibrahim/.local/share/Geode/cross-tools/splat/sdk/lib/um/x86_64" -L"/home/ibrahim/Downloads/GrandpaDemon-main/build-win/winsdk_lib_symlinks"  -Xlinker /subsystem:console @CMakeFiles/cmTC_51ffc.dir/objects1.rsp -o cmTC_51ffc.exe -Xlinker /MANIFEST:EMBED -Xlinker /implib:cmTC_51ffc.lib -Xlinker /pdb:/home/ibrahim/Downloads/GrandpaDemon-main/build-win/CMakeFiles/CMakeScratch/TryCompile-Z0vSQj/cmTC_51ffc.pdb -Xlinker /version:0.0  @CMakeFiles/cmTC_51ffc.dir/linkLibs.rsp 
        clang-18: error: unable to execute command: Executable "lld-link" doesn't exist!
        clang-18: error: linker command failed with exit code 1 (use -v to see invocation)
        gmake[1]: *** [CMakeFiles/cmTC_51ffc.dir/build.make:102: cmTC_51ffc.exe] Error 1
        gmake[1]: Leaving directory '/home/ibrahim/Downloads/GrandpaDemon-main/build-win/CMakeFiles/CMakeScratch/TryCompile-Z0vSQj'
        gmake: *** [Makefile:127: cmTC_51ffc/fast] Error 2
        
      exitCode: 2
...
